// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymkybarpnmyewvksrnfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlta3liYXJwbm15ZXd2a3NybmZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3ODYxOTgsImV4cCI6MjA2OTM2MjE5OH0.3hgkotaVxGu_t329uxOGXehzPOisoSGJS6F4Mi0o-WU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});